# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:
  en: The web by Paul
  fr: L'web selon Paul
email: paul@enfluence.io
description:
  en: Reflecting on the internet of us
  fr: Réflexions sur l'internet de nous
index:
  en:
  fr: accueil.html
feed:
  en: /feed.xml
  fr: /flux.xml
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://pcuci.github.io" # the base hostname & protocol for your site
twitter_username: pcuci
github_username: pcuci

# Build settings
markdown: kramdown
